name: kues
description: My flutter app for Keus
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_mobx: ^2.0.6+5
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  get_it_mixin: ^4.2.0
  google_fonts: ^6.2.1
  material_color_utilities: ^0.11.1
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  stream_transform: ^2.1.0
  mobx: ^2.5.0
  meta: ^1.9.1
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.2
  test: ^1.24.1
  mockingjay: ^0.5.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true
